name: HashiCorp Registry Backend Monitor (Cache-Based)

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering for testing

permissions:
  contents: read  # No longer need write permissions for git
  issues: write

jobs:
  monitor-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Create output directory
      run: mkdir -p results
    
    - name: Restore previous scan results
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: results/previous-scan.json
        key: backend-scan-never-match  # Force restore from restore-keys
        restore-keys: |
          backend-scan-previous
    
    - name: Run backend discovery
      run: |
        python3 provenance_discovery.py --output json > results/current-scan.json
      env:
        # Add any authentication if needed
        # REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        # REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Compare with previous results
      id: compare
      run: |
        python3 .github/scripts/compare_cached_results.py
      continue-on-error: true
    
    - name: Create alert issue on changes
      if: steps.compare.outputs.changes_detected == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          // Read the comparison report
          const reportPath = 'results/comparison-report.md';
          let reportContent = 'Comparison report not found.';
          
          if (fs.existsSync(reportPath)) {
            reportContent = fs.readFileSync(reportPath, 'utf8');
          }
          
          // Create issue with alert
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🚨 HashiCorp Registry Backend Changes Detected - ${new Date().toISOString().split('T')[0]}`,
            body: `## Backend Infrastructure Changes Detected
          
          The daily HashiCorp registry backend scan has detected changes in the underlying S3 infrastructure.
          
          **Scan Date:** ${new Date().toISOString()}
          **Repository:** hashicorp/terraform-enterprise
          **Registry:** https://images.releases.hashicorp.com
          
          ${reportContent}
          
          ## What This Means
          
          Changes in S3 endpoints could indicate:
          - Infrastructure updates by HashiCorp
          - Changes in container image distribution
          - Backend storage modifications
          
          ## Recommended Actions
          
          1. Review the detailed changes above
          2. Verify changes align with known HashiCorp infrastructure updates
          3. Update any infrastructure allowlists if needed
          4. Monitor for additional changes in subsequent scans
          
          ---
          *This alert was automatically generated by the [HashiCorp Registry Backend Monitor](/.github/workflows/backend-monitor.yml)*`,
            labels: ['backend-alert', 'infrastructure', 'automated']
          });
    
    - name: Save current scan for next run
      uses: actions/cache/save@v4
      with:
        path: results/current-scan.json
        key: backend-scan-previous-${{ github.run_number }}
    
    - name: Upload current scan as artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: backend-scan-${{ github.run_number }}
        path: results/current-scan.json
        retention-days: 7  # Keep for 1 week only